Repository anelissao/Youcode-thrid-brief, pull requests merged in 2024-10, with the labels that each got.

#56 Mustap d01 a card about
  about.html
  source/css/style_page_about/style_about.css
  source/img/images_page_abput/image-4.jpg
  source/img/images_page_abput/image-about.jpg
  source/img/images_page_abput/team-1.jpg
  source/img/images_page_abput/team-2.jpg
  source/img/images_page_abput/team-3.jpg
  source/img/images_page_abput/user-1.jpg
  source/img/images_page_abput/user-2.jpg
  source/img/images_page_abput/user-3.jpg
Labels: in review

#57 Safett d01 c card cont
  contact.css
  contact.html
Labels: in review

#60 Safett d01 c maps
  contact.html
  source/css/contact.css
Labels: in review

#63 Mustap d01 a card client
  about.html
  source/css/style_page_about/style_about.css
  source/css/style_principale.css
Labels: in review

#64 Safett d01 c login
  login.html
  source/css/login.css
Labels: in review

#66 Mustap d01 navbar and footer
  about.html
  source/css/style_page_about/style_about.css
  source/css/style_principale.css
  source/img/logo/logo-rekrute.png
  source/js/app.js
Labels: in review

#67 I add card principale
  blog.html
  source/css/style_page_blogs/blog-style.css
  source/img/Image-blog/a1.jpg
  source/img/Image-blog/a2.jpg
  source/img/Image-blog/a3.jpg
  source/img/Image-blog/a4.jpg
  source/img/Image-blog/p-1.jpg
  source/img/Image-blog/p-2.jpg
  source/img/Image-blog/p-3.jpg
  source/img/Image-blog/p-4.jpg
Labels: ready to merge

#69 Saadq d01 j cards jobs
  jobs-page-styling.css
  jobs-page.html
  source/img/jobs-imgs/companies-imgs/figma.png
  source/img/jobs-imgs/companies-imgs/google.png
  source/img/jobs-imgs/companies-imgs/microsoft.png
Labels: ready to merge

#72 Safett d01 c contact vf
  contact.css
  contact.html
  login.html
  source/css/contact.css
Labels: ready to merge

#74 Safett d01 c register
  register.html
  source/css/register.css
Labels: ready to merge

#77 Saad1 d01 j caregories
  jobs-page-styling.css
  jobs-page.html
Labels: enhancement

#79 finish the last ticket
  blog.html
  source/css/style_page_blogs/blog-style.css
  source/img/Image-blog/a4.jpg
Labels: ready to merge

#84 Connect pages
  about.html
  blog.html
  contact.html
  index.html
  jobs-page-styling.css
  jobs-page.html
  source/css/style.css
Labels: ready to merge
